repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-json
    - id: check-yaml
    - id: debug-statements
    - id: requirements-txt-fixer
    - id: flake8
